config/routes.rb
Moneymouth::Application.routes.draw do
  root :to => 'user_sessions#new'

  resources :users, :user_sessions

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'signup' => 'users#new', :as => :signup
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation

  acts_as_authentic do |c|
    c.login_field = 'email'
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  extend ActiveSupport::Memoizable
  protect_from_forgery

  helper_method :current_user_session, :current_user

  private

  def current_user_session
    @current_user_session = UserSession.find
  end
  memoize :current_user_session

  def current_user
    @current_user = current_user_session && current_user_session.user
  end
  memoize :current_user

  def require_user
    unless current_user
      session[:return_to] = request.get? ? request.request_uri : request.referer
      flash[:notice] = "Please log in to view this page."
      redirect_to new_user_session_url
      return false
    end
  end

  def redirect_back_or_default(default)
    redirect_to(session[:return_to] || default)
    session[:return_to] = nil
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_user, :only => :destroy

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "You are now logged in."
      redirect_back_or_default login_url(@current_user)
    else
      render :action => :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:notice] = "You are now logged out."
    redirect_back_or_default new_user_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Welcome to MoneyMouth!"
      redirect_to signup_url
    else
      flash[:notice] = "There was a problem creating your user."
      render :action => :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!! HTML
%head
  %title MoneyMouth
  .user_session_info
    - if current_user
      You are logged in as #{current_user.email}
      = link_to "Logout", logout_path
    - else
      = link_to "Login", login_path
      = link_to "Register", signup_path

  = stylesheet_link_tag "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags

%body
  - if flash[:alert]
    %p.flash_error= flash[:alert]
  - if flash[:notice]
    %p.flash_notice= flash[:notice]

  = yield

app/views/shared/_error_messages.html.haml
- unless target.errors.empty?
  %h3 There were problems:
  %ul
    - target.errors.full_messages.each do |error_message|
      %li
        = error_message

app/views/user_sessions/new.html.haml
%h1 Login


- if current_user
  You are already logged in.
- else
  = render 'shared/error_messages', :target => @user_session

  = form_for(@user_session) do |f|
    = f.label :email
    = f.text_field :email
    %br
      = f.label :password
      = f.password_field :password
      %br
        = f.submit "Login"

app/views/users/_form.html.haml
= render 'shared/error_messages', :target => @user

= form.label :email
= form.text_field :email
%br
= form.label :password, form.object.new_record? ? nil : "New Password"
= form.password_field :password
%br
= form.label :password_confirmation, "Password Confirmation"
= form.password_field :password_confirmation
%br

app/views/users/new.html.haml
%h1 Register

= form_for @user do |f|
  = render :partial => 'form', :object => f, :locals => { :user => @user }
  = f.submit "Register"